### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by bknowles** [ewebdevelopment/sw-galaxy#16]
Going to the page at https://ewebdevelopment.github.io/sw-galaxy I get a 404.

is the site down, or is there something else going on?

**Comment by applifaction** [comment]
Hi, 

i changed my username. Therefore the URL of the website changed as well. The new link is: https://applifaction.github.io/sw-galaxy

I updated the link in the readme file as well.

**Comment by bknowles** [comment]
I will spread word of this URL change. Thanks!

**Comment by applifaction** [comment]
Thank you :)
