### ISSUE TITLE
Sticky table header

### ISSUE THREAD

**Issue by applifaction** [ewebdevelopment/sw-galaxy#2]
Would it be possible to have the column headers stay at the top of the screen as you scroll down? That way you don't have to scroll all the way back to the top if you forget which column is enc, rarity, etc.

**Comment by applifaction** [comment]
I tested your feature with different mobile resolutions. Unfortunately if you change the resolutions multiple times, the table size will be adjusted to a very small height. 

![image](https://user-images.githubusercontent.com/9271838/28065777-6fa5073c-663a-11e7-8adc-633ff9708229.png)

**Comment by applifaction** [comment]
@MarceloAlves Do you want to find a solution for it or should i or @Dutzen fix this?

**Comment by MarceloAlves** [comment]
Hmm. Well `max-height` is calculated when the page is rendered. After going into responsive mode and refreshing it works out okay but there's gotta be a better way to handle this. If you guys wouldn't mind taking a look that would be 👍

**Comment by applifaction** [comment]
I tried to make the table header sticky while i implemented the web app too. I used the same dependency as you (`fixed.table.header`). I had the same bug as you. I realized that it would consume more time than initially thought to fix this in a **nice** way. Therefore i reverted my changes and worked on other features.

I will try to find a fancy solution for it when i have some spare time.

**Comment by applifaction** [comment]
I just realized that my commit broke possibility to scroll to the right on desktops. Therefore i reverted the merge. I will continue to fix this later.

**Comment by applifaction** [comment]
I fixed the wrong scrolling behavior and merged this feature into the master branch.
